name: Generate Snake (Manual)

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Your GitHub username'
        default: 'taegangkim'
        required: true
        type: string

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: ${{ inputs.username }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
